trigger:
- dev

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'Koti_Paid (b321893b-78f2-4e98-b106-8c4a140e2f83)'

  # Function app name
  functionAppName: 'kotitestapp'

  # Agent VM image name
  vmImageName: 'windows-latest'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:

    - task: UsePythonVersion@0

    - script: 'python -m pip install -r requirements.txt'
      workingDirectory: $(workingDirectory)
      displayName: 'Install application dependencies'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
            - script: |
                az login --service-principal -u 7b7c1274-dee1-4a9b-9c6b-421284d3698c -p Lm28Q~.ZrFA4Nw24YIuTXSOYzCv6gpLdIdNo0cUE --tenant e50ac971-3d9f-4814-8280-e149c3a0d801
              displayName: 'Azure CLI login'

            - task: AzureFunctionApp@1
              displayName: 'Azure functions app deploy'
              inputs:
                azureSubscription: 'Koti_Paid (b321893b-78f2-4e98-b106-8c4a140e2f83)'
                appType: 'functionAppLinux'
                appName: '$(functionAppName)'
                package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                deploymentMethod: 'runFromPackage'
